version: "3.8"


networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      PACKWIZ_URL: https://raw.githubusercontent.com/dovisp/aSimpleSMPPack/main/pack.toml
      DIFFICULTY: "HARD"
      ENABLE_COMMAND_BLOCK: "true"
      ONLINE_MODE: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      LEVEL_TYPE: "terra:overworld/overworld"
      USE_AIKAR_FLAGS: "TRUE"
      MAX_MEMORY: 2G
      STOP_SERVER_ANNOUNCE_DELAY: 10
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./mc-server:/data
    networks:
      main:
        ipv4_address: 172.20.0.10
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./plex/config:/config
      - /data/media/tv:/tv
      - /data/media/movies:/movies
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/config:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.0.3
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optionall
    volumes:
      - ./jackett/config:/config
      - /data/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.0.2
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbit/config:/config
      - /data/torrents:/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.0.5
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.0.6
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Etc/UTC'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole:/pihole'
      - './etc-dnsmasq.d:/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    networks:
      main:
        ipv4_address: 172.20.0.7
    restart: unless-stopped
