version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      PACKWIZ_URL: https://raw.githubusercontent.com/dovisp/aSimpleSMPPack/main/pack.toml
      DIFFICULTY: "HARD"
      ENABLE_COMMAND_BLOCK: "true"
      ONLINE_MODE: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      LEVEL_TYPE: "terra:overworld/overworld"
      USE_AIKAR_FLAGS: "TRUE"
      MAX_MEMORY: 2G
      STOP_SERVER_ANNOUNCE_DELAY: 10
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./mc-server:/data
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped
